default: &default
  adapter: postgresql
  encoding: unicode
  username: elly
  password: immortal
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecash_development

test:
  <<: *default
  database: ecash_test

production:
  <<: *default
  database: ecash_production
  username: ecash
  password: <%= ENV['ECASH_DATABASE_PASSWORD'] %>
